// app/layout.jsx
import localFont from "next/font/local";
import "./globals.css";
import ClientLayout from "./client-layout";

const heveria = localFont({
  src: [
    {
      path: "../public/fonts/Heveria-Medium-Trial-BF66b193b1d1fb0.otf",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-heveria",
  display: "swap",
});

export const metadata = {
  title: "FxS BOT",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${heveria.variable}`} suppressHydrationWarning>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
